import { useMemo, useState } from "react";
import { Link } from "react-router-dom";

import { Disclaimer } from "../components/Disclaimer";
import { MachineCard } from "../components/MachineCard";
import { StatCard } from "../components/StatCard";
import { TrackerMascot } from "../components/TrackerMascot";
import { icons } from "../components/icons";
import { useDashboardData } from "../hooks/useDashboardData";
import { locationConfig } from "../lib/config";
import { type SortKey, sortMachines, sortOptions } from "../lib/data";
import { formatRelative } from "../lib/format";

export function Dashboard({ view = "dashboard" }: { view?: "dashboard" | "machines" }) {
  const isMachineDirectory = view === "machines";
  const { data, loading, error, reload } = useDashboardData();
  const [sortKey, setSortKey] = useState<SortKey>("probability");

  const machines = useMemo(
    () => (data ? sortMachines(data.machines, sortKey) : []),
    [data, sortKey],
  );

  const zipCode = data?.search.zipCode ?? locationConfig.zipCode;
  const radiusMiles = data?.search.radiusMiles ?? locationConfig.radiusMiles;

  const scored = machines.filter((entry) => entry.forecast?.status === "OK").length;
  const networkPattern = machines.filter(
    (entry) => entry.forecast?.status === "NETWORK_PATTERN",
  ).length;
  const collecting = machines.length - scored - networkPattern;

  return (
    <>
      <header className="page-head">
        <TrackerMascot />
        <div className="page-head__row">
          <span className="page-head__pin" aria-hidden="true">
            {icons.pin}
          </span>
          <div>
            <h1 className="page-head__title">
              {isMachineDirectory ? "Machines" : `Machines near ${zipCode}`}
            </h1>
            <p className="page-head__sub">
              {isMachineDirectory
                ? `Browse machines near ${zipCode}. Select one for forecasts, reports, and directions.`
                : "When is a machine near you most likely to dispense a product?"}
            </p>
            <p className="page-head__meta">
              Within {radiusMiles} miles
              <span className="page-head__dot">·</span>
              Updated {data ? formatRelative(data.generatedAt) : "—"}
              {!isMachineDirectory && (
                <Link className="button button--small" to="/machines">Browse machines →</Link>
              )}
            </p>
          </div>
        </div>
      </header>

      {data?.demoData && (
        <div className="banner banner--demo" role="alert">
          <p>
            <strong>Demonstration data.</strong> These observations are synthetic, generated by{" "}
            <code>pokevend.jobs.seed_demo</code> so the forecast views can be exercised. The
            machines and distances are real; the availability reports are not.
          </p>
        </div>
      )}

      {error && (
        <div className="banner banner--error" role="alert">
          <p>Could not load forecast data: {error}</p>
          <p className="banner__hint">
            Run the ingestion jobs to generate <code>apps/web/public/data/</code>, then reload.
          </p>
          <button type="button" className="button button--small" onClick={reload}>
            Retry
          </button>
        </div>
      )}

      {data?.errors.map((message) => (
        <div key={message} className="banner banner--warning" role="status">
          {message}
        </div>
      ))}

      {loading && !data && <p className="empty-note">Loading forecast data…</p>}

      {data && (
        <>
          {!isMachineDirectory && <div className="stat-row">
            <StatCard
              icon={icons.pin}
              title="Machines in range"
              value={String(machines.length)}
              detail={`Within ${radiusMiles} miles of ${zipCode}`}
            />
            <StatCard
              icon={icons.pulse}
              title="Own-history forecasts"
              value={String(scored)}
              tone={scored > 0 ? "good" : "muted"}
              detail={
                scored > 0
                  ? "Scored from their own reports"
                  : "None have enough reports yet"
              }
            />
            <StatCard
              icon={icons.clock}
              title="Regional pattern"
              value={String(networkPattern)}
              tone={networkPattern > 0 ? "default" : "muted"}
              detail="Using the wider community rate"
            />
            <StatCard
              icon={icons.doc}
              title="Observations"
              value={String(data.observationCount)}
              detail={
                <>
                  Ingested overall ·{" "}
                  <Link to="/sources" className="stat-card__link">
                    sources
                  </Link>
                </>
              }
            />
          </div>}

          <section id="machines">
            <div className="section-head">
              <h2 className="section-title">
                All machines
                <span className="section-title__count">
                  {scored} own history · {networkPattern} regional · {collecting} collecting
                </span>
              </h2>

              <label className="sort">
                <span>Sort by</span>
                <select
                  value={sortKey}
                  onChange={(event) => setSortKey(event.target.value as SortKey)}
                >
                  {sortOptions.map((option) => (
                    <option key={option.key} value={option.key}>
                      {option.label}
                    </option>
                  ))}
                </select>
              </label>
            </div>

            {machines.length === 0 ? (
              <p className="empty-note">
                No machines were found within {radiusMiles} miles of {zipCode}.
              </p>
            ) : (
              <div className="machine-grid">
                {machines.map((entry) => (
                  <MachineCard key={entry.machine.id} entry={entry} />
                ))}
              </div>
            )}
          </section>
        </>
      )}

      <Disclaimer />
    </>
  );
}
