import { useMemo, useState } from "react";

import { Disclaimer } from "../components/Disclaimer";
import { PokeballMark } from "../components/PokeballMark";
import { MachineCard } from "../components/MachineCard";
import { SourceHealthPanel } from "../components/SourceHealthPanel";
import { useDashboardData } from "../hooks/useDashboardData";
import { locationConfig } from "../lib/config";
import { type SortKey, sortMachines, sortOptions } from "../lib/data";
import { formatRelative } from "../lib/format";

export function Dashboard() {
  const { data, loading, error, reload } = useDashboardData();
  const [sortKey, setSortKey] = useState<SortKey>("probability");

  const machines = useMemo(
    () => (data ? sortMachines(data.machines, sortKey) : []),
    [data, sortKey],
  );

  const zipCode = data?.search.zipCode ?? locationConfig.zipCode;
  const radiusMiles = data?.search.radiusMiles ?? locationConfig.radiusMiles;

  const scored = machines.filter((entry) => entry.forecast?.status === "OK").length;
  const networkPattern = machines.filter(
    (entry) => entry.forecast?.status === "NETWORK_PATTERN",
  ).length;
  const collecting = machines.length - scored - networkPattern;

  return (
    <div className="page">
      <header className="hero">
        <PokeballMark className="hero__mark" />
        <p className="eyebrow">
          <span className="eyebrow__dot" aria-hidden="true" />
          Community stock intelligence
        </p>
        <h1 className="hero__title">Pokémon Vending Forecast</h1>
        <p className="hero__subtitle">
          Find the best time to check a nearby machine, powered by community reports and
          local availability patterns.
        </p>
        <dl className="hero__search">
          <div>
            <dt>Search area</dt>
            <dd>{zipCode}</dd>
          </div>
          <div>
            <dt>Radius</dt>
            <dd>{radiusMiles} miles</dd>
          </div>
          <div>
            <dt>Forecast data updated</dt>
            <dd>{data ? formatRelative(data.generatedAt) : "—"}</dd>
          </div>
        </dl>
      </header>

      {data?.demoData && (
        <div className="banner banner--demo" role="alert">
          <p>
            <strong>Demonstration data.</strong> These observations are synthetic, generated by{" "}
            <code>pokevend.jobs.seed_demo</code> so the forecast views can be exercised. The
            machines and distances are real; the availability reports are not.
          </p>
        </div>
      )}

      {error && (
        <div className="banner banner--error" role="alert">
          <p>Could not load forecast data: {error}</p>
          <p className="banner__hint">
            Run the ingestion jobs to generate <code>apps/web/public/data/</code>, then reload.
          </p>
          <button type="button" className="button button--small" onClick={reload}>
            Retry
          </button>
        </div>
      )}

      {data?.errors.map((message) => (
        <div key={message} className="banner banner--warning" role="status">
          {message}
        </div>
      ))}

      {loading && !data && <p className="empty-note">Loading forecast data…</p>}

      {data && (
        <>
          <section className="machine-section">
            <div className="section-head">
              <h2 className="section-title">
                Nearby machines
                <span className="section-title__count">
                  {machines.length} within {radiusMiles} miles
                </span>
              </h2>

              <label className="sort">
                <span>Sort by</span>
                <select
                  value={sortKey}
                  onChange={(event) => setSortKey(event.target.value as SortKey)}
                >
                  {sortOptions.map((option) => (
                    <option key={option.key} value={option.key}>
                      {option.label}
                    </option>
                  ))}
                </select>
              </label>
            </div>

            <div className="summary-grid" aria-label="Forecast coverage">
              <div className="summary-card summary-card--scored">
                <strong>{scored}</strong>
                <span>Machine forecast{scored === 1 ? "" : "s"}</span>
              </div>
              <div className="summary-card summary-card--network">
                <strong>{networkPattern}</strong>
                <span>Regional pattern{networkPattern === 1 ? "" : "s"}</span>
              </div>
              <div className="summary-card summary-card--collecting">
                <strong>{collecting}</strong>
                <span>Still collecting</span>
              </div>
              <div className="summary-card summary-card--reports">
                <strong>{data.observationCount}</strong>
                <span>Report{data.observationCount === 1 ? "" : "s"} analyzed</span>
              </div>
            </div>

            {machines.length === 0 ? (
              <p className="empty-note">
                No machines were found within {radiusMiles} miles of {zipCode}.
              </p>
            ) : (
              <div className="machine-grid">
                {machines.map((entry) => (
                  <MachineCard key={entry.machine.id} entry={entry} />
                ))}
              </div>
            )}
          </section>

          <SourceHealthPanel sources={data.sources} />
        </>
      )}

      <Disclaimer />
    </div>
  );
}
